### ISSUE TITLE
[bug] Potential bugs, check if still exist

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/plotr#4]
- [x] wrong ranges in post processing preview?: https://github.com/INWT/mpi-plotr/issues/77
![image](https://user-images.githubusercontent.com/16759098/155535390-5a037969-345f-4287-a6e6-487ffe892d72.png)

- [x] when adding points: missing value where TRUE/FALSE needed: https://github.com/INWT/mpi-plotr/issues/58
  -> not occurring anymore

![image](https://user-images.githubusercontent.com/73887426/138099101-7aa15b0a-2ca2-4665-8795-5394847fb93e.png)
  
- [x] Warning if browsing another file without accepting the first one: https://github.com/INWT/mpi-plotr/issues/55
  -> not occurring anymore
```R
! Multiple files in zip: reading ''_rels/.rels''
```

- [x] warning if NAs/char in data: https://github.com/INWT/mpi-plotr/issues/34
  -> not occuring anymore
> nach dem fix https://github.com/INWT/mpi-plotr/commit/443fa076b9626e01c86df742008f5baa6e1d6c22 gibt es das Warning nicht mehr in der Preview, allerdings noch danach sobald _Accept_ gedrückt wurde:
> ![image](https://user-images.githubusercontent.com/16759098/129870151-72ee173e-1e69-4d2c-ba8f-e3a3311005fc.png)

**Comment by arunge** [comment]
Regarding above:
> wrong ranges in post processing preview?: https://github.com/INWT/mpi-plotr/issues/77

The range was fixed and the plot is displayed correctly:

![image](https://user-images.githubusercontent.com/16759098/204796465-49866150-1327-401c-88bc-bf71fb1835ce.png)
