### ISSUE TITLE
Documentation, R-CMD Check, rm rgpt3 & NEWS

### ISSUE THREAD

**Issue by jan-abel-inwt** [Pandora-IsoMemo/plotr#44]
- [x] [Package Documentation with pkgdown](https://github.com/Pandora-IsoMemo/docs/issues/11)
- [x] [r-cmd check via github actions](https://github.com/Pandora-IsoMemo/docs/issues/12)
- [x] [Improve Dependency Management - remove `rgpt3`](https://github.com/Pandora-IsoMemo/drat/issues/33)
- [x] [Ensure compliance of CRAN Standard in NEWS File](https://github.com/Pandora-IsoMemo/drat/issues/34)
